version: 3.3;

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - db_pgsql
    ports:
      - "9000:9000"
  db_pgsql:
    image: postgres:14.10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test-crop-image
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753159753
    volumes:
      - ./postgresql:/var/lib/postgresql
