# fly.toml app configuration file generated for test-assignment-nginx on 2024-02-10T21:47:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-assignment-nginx"
primary_region = "waw"

[build]
  dockerfile = "./nginx.dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
