# fly.toml app configuration file generated for test-assignment-db on 2024-02-10T20:22:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-assignment-db"
primary_region = "waw"

[build]
  image = "postgres:14.10-alpine"

[[mounts]]
  source = "psql_data"
  destination = "/var/lib/postgresql/"
